name: Build and push docker image

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wiktorjedski/nodejs-sample
          tags: |
            type=sha
            type=ref,event=branch
            type=match,pattern=v?(?P<major>\d+).(?P<minor>\d+).(?P<patch>\d+),event=tag
            type=semver,pattern=v{{version}}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.output.labels }}

      - name: Output tags for the next job
        run: |
          echo "${{ steps.meta.output.tags }}"
